apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zeqpu43ox-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-3ea828ac69.q9y4.p3.openshiftapps.com/rhtap/rhtap-qe:60287295bf89026bd20a71ba681f804e157d847c@sha256:634596d05a4a2d10ef0e7f8080c33c9b1f41ad1b34ff5d4653efb5e53684bbce
          name: container-image
